const DEFAULT_PAGE = 1
const DEFAULT_SIZE = 20
// const DEFAULT_ROW_SIZE = 10;
// const DEFAULT_COLUMN_HEIGHT = 70;
const DEFAULT_PAGE_SIZE_OPTIONS = [1, 2, 10, 20, 50, 100]

export { DEFAULT_PAGE, DEFAULT_SIZE, DEFAULT_PAGE_SIZE_OPTIONS }
